version: '2'
services:
  golos:
    build:
      args:
        - GOLOS_FC_GIT_REVISION_SHA
        - GOLOS_FC_GIT_REVISION_UNIX_TIMESTAMP
        - GOLOS_GRAPHENE_GIT_REVISION_SHA
        - GOLOS_GRAPHENE_GIT_REVISION_UNIX_TIMESTAMP
        - GOLOS_GRAPHENE_GIT_REVISION_DESCRIPTION
        - GOLOS_BUILD_TYPE
        - GOLOS_THREADS_BUILD
        - GOLOS_SHARED_BUILD
        - GOLOS_MONGO_PLUGIN
        - GOLOS_MAX_19_VOTED_WITNESSES
        - GOLOS_CHAINBASE_CHECK_LOCKING
        - GOLOS_TESTNET
        - GOLOS_COVERAGE_TESTING
      context: golos
    environment:
      GOLOS_P2P_PORT:
      GOLOS_RPC_HTTP_PORT:
      GOLOS_RPC_WS_PORT:
    ports:
     - "${GOLOS_P2P_HOST_PORT}:${GOLOS_P2P_PORT}"
     - "${GOLOS_RPC_HTTP_HOST_PORT}:${GOLOS_RPC_HTTP_PORT}"
     - "${GOLOS_RPC_WS_HOST_PORT}:${GOLOS_RPC_WS_PORT}"
    volumes:
     - golos_volume:/var/lib/golosd
     - ./conf/golos_witness_node_config.ini:/var/lib/golosd/config.ini
    restart: always
  tolstoy-db:
    environment:
      MYSQL_ROOT_PASSWORD: ${TOLSTOY_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${TOLSTOY_MYSQL_USER}
      MYSQL_PASSWORD: ${TOLSTOY_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${TOLSTOY_MYSQL_DATABASE}
    image: mysql:latest
    volumes:
     - tolstoy_db_volume:/var/lib/mysql
    restart: always
  tolstoy-cache:
    environment:
      TARANTOOL_PORT: ${TOLSTOY_TARANTOOL_PORT}
      TARANTOOL_USER_NAME: ${TOLSTOY_TARANTOOL_USER}
      TARANTOOL_USER_PASSWORD: ${TOLSTOY_TARANTOOL_PASSWORD}
    image: tarantool/tarantool:latest
    volumes:
     - tolstoy_cache_volume:/var/lib/tarantool
    restart: always
  imagehoster-cache:
    build: imagehoster/ttdatastore
    environment:
      TARANTOOL_PORT: ${IMAGEHOSTER_TARANTOOL_PORT}
      TARANTOOL_USER_NAME: ${IMAGEHOSTER_TARANTOOL_USER}
      TARANTOOL_USER_PASSWORD: ${IMAGEHOSTER_TARANTOOL_PASSWORD}
    volumes:
     - imagehoster_cache_volume:/var/lib/tarantool
    restart: always
  imagehoster:
    build: imagehoster/imagehoster
    environment:
      STEEMIT_UPLOAD_STEEMD_WEBSOCKET: ${IMAGEHOSTER_UPLOAD_STEEMD_WEBSOCKET}
      STEEMIT_UPLOAD_HTTP_PROTOCOL: ${IMAGEHOSTER_UPLOAD_HTTP_PROTOCOL}
      STEEMIT_UPLOAD_HTTP_HOST: ${IMAGEHOSTER_UPLOAD_HTTP_HOST}
      STEEMIT_TARANTOOL_HOST: imagehoster-cache
      STEEMIT_TARANTOOL_PORT: ${IMAGEHOSTER_TARANTOOL_PORT}
      STEEMIT_TARANTOOL_USERNAME: ${IMAGEHOSTER_TARANTOOL_NAME}
      STEEMIT_TARANTOOL_PASSWORD: ${IMAGEHOSTER_TARANTOOL_PASSWORD}
      STEEMIT_UPLOAD_TEST_KEY: ${IMAGEHOSTER_UPLOAD_TEST_KEY}
      STEEMIT_UPLOAD_MIN_REP: ${IMAGEHOSTER_UPLOAD_MIN_REP}
      STEEMIT_IMAGE_BUCKET_UPLOAD: ${IMAGEHOSTER_IMAGE_BUCKET_UPLOAD}
      STEEMIT_IMAGEPROXY_BUCKET_WEB: ${IMAGEHOSTER_IMAGEPROXY_BUCKET_WEB}
      STEEMIT_IMAGEPROXY_BUCKET_THUMBNAIL: ${IMAGEHOSTER_IMAGEPROXY_BUCKET_THUMBNAIL}
    depends_on:
      - golos
      - imagehoster-cache
    restart: always
  tolstoy:
    build:
      context: tolstoy
    depends_on:
      - golos
      - tolstoy-db
    environment:
      PORT: ${TOLSTOY_PORT}
      SDC_DATABASE_URL: mysql://${TOLSTOY_MYSQL_USER}:${TOLSTOY_MYSQL_PASSWORD}@tolstoy-db/${TOLSTOY_MYSQL_DATABASE}
      SDC_DISABLE_SIGNUPS: ${TOLSTOY_DISABLE_SIGNUPS}
      SDC_FACEBOOK_APP_ID: ${TOLSTOY_FACEBOOK_APP_ID}
      SDC_VK_PIXEL_ID: ${TOLSTOY_VK_PIXEL_ID}
      SDC_FB_API_KEY: ${TOLSTOY_FB_API_KEY}
      SDC_FB_API_SECRET: ${TOLSTOY_FB_API_SECRET}
      SDC_REDDIT_API_KEY: ${TOLSTOY_REDDIT_API_KEY}
      SDC_REDDIT_API_SECRET: ${TOLSTOY_REDDIT_API_SECRET}
      SDC_VK_API_KEY: ${TOLSTOY_VK_API_KEY}
      SDC_VK_API_SECRET: ${TOLSTOY_VK_API_SECRET}
      SDC_GRANT_HOST: ${TOLSTOY_GRANT_HOST}
      SDC_GRANT_PROTOCOL: ${TOLSTOY_GRANT_PROTOCOL}
      SDC_GOOGLE_ANALYTICS_ID: ${TOLSTOY_GOOGLE_ANALYTICS_ID}
      SDC_HELMET_CHILDSRC: ${TOLSTOY_HELMET_CHILDSRC}
      SDC_HELMET_CONNECTSRC: ${TOLSTOY_HELMET_CONNECTSRC}
      SDC_HELMET_DEFAULTSRC: ${TOLSTOY_HELMET_DEFAULTSRC}
      SDC_HELMET_FONTSRC: ${TOLSTOY_HELMET_FONTSRC}
      SDC_HELMET_FRAMEANCESTORS: ${TOLSTOY_HELMET_FRAMEANCESTORS}
      SDC_HELMET_IMGSRC: ${TOLSTOY_HELMET_IMGSRC}
      SDC_HELMET_OBJECTSRC: ${TOLSTOY_HELMET_OBJECTSRC}
      SDC_HELMET_SCRIPTSRC: ${TOLSTOY_HELMET_SCRIPTSRC}
      SDC_HELMET_STYLESRC: ${TOLSTOY_HELMET_STYLESRC}
      SDC_IMAGE_PROXY_PREFIX: ${TOLSTOY_IMAGE_PROXY_PREFIX}
      SDC_MIXPANEL: ${TOLSTOY_MIXPANEL}
      SDC_NOTIFY_GCM_KEY: ${TOLSTOY_NOTIFY_GCM_KEY}
      SDC_READONLY_MODE: ${TOLSTOY_READONLY_MODE}
      SDC_RECAPTCHA_SECRET_KEY: ${TOLSTOY_RECAPTCHA_SECRET_KEY}
      SDC_RECAPTCHA_SITE_KEY: ${TOLSTOY_RECAPTCHA_SITE_KEY}
      SDC_REGISTRAR_ACCOUNT: ${TOLSTOY_REGISTRAR_ACCOUNT}
      SDC_REGISTRAR_AMOUNT: ${TOLSTOY_REGISTRAR_FEE}
      SDC_REGISTRAR_SIGNINGKEY: ${TOLSTOY_REGISTRAR_WIF}
      SDC_RECOVERY_ACCOUNT: ${TOLSTOY_RECOVERY_ACCOUNT}
      SDC_RECOVERY_SIGNINGKEY: ${TOLSTOY_RECOVERY_WIF}
      SDC_SENDGRID_FROM: ${TOLSTOY_SENDGRID_FROM}
      SDC_SENDGRID_API_KEY: ${TOLSTOY_SENDGRID_API_KEY}
      SDC_SENDGRID_CONFIRMTEMPLATE: ${TOLSTOY_SENDGRID_CONFIRMTEMPLATE}
      SDC_SENDGRID_WAITINGTEMPLATE: ${TOLSTOY_SENDGRID_WAITINGTEMPLATE}
      SDC_POSTMARK_FROM: ${TOLSTOY_POSTMARK_FROM}
      SDC_POSTMARK_API_KEY: ${TOLSTOY_POSTMARK_API_KEY}
      SDC_POSTMARK_CONFIRMTEMPLATE: ${TOLSTOY_POSTMARK_CONFIRMTEMPLATE}
      SDC_POSTMARK_WAITINGTEMPLATE: ${TOLSTOY_POSTMARK_WAITINGTEMPLATE}
      SDC_SESSION_SECRETKEY: ${TOLSTOY_SESSION_SECRETKEY}
      SDC_SITE_DOMAIN: ${TOLSTOY_SITE_DOMAIN}
      SDC_TARANTOOL_HOSTNAME: tolstoy-cache
      SDC_TARANTOOL_PORT: ${TOLSTOY_TARANTOOL_PORT}
      SDC_TARANTOOL_USERNAME: ${TOLSTOY_TARANTOOL_USER}
      SDC_TARANTOOL_PASSWORD: ${TOLSTOY_TARANTOOL_PASSWORD}
      SDC_CHAIN_PROXY_HOSTNAME: ${TOLSTOY_CHAIN_PROXY_HOSTNAME}
      SDC_CHAIN_PROXY_PASSWORD: ${TOLSTOY_CHAIN_PROXY_PASSWORD}
      SDC_CHAIN_PROXY_PORT: ${TOLSTOY_CHAIN_PROXY_PORT}
      SDC_CHAIN_PROXY_USERNAME: ${TOLSTOY_CHAIN_PROXY_USERNAME}
      SDC_TELESIGN_CUSTOMER_ID: ${TOLSTOY_TELESIGN_CUSTOMER_ID}
      SDC_TELESIGN_API_KEY: ${TOLSTOY_TELESIGN_API_KEY}
      SDC_TWILIO_ACCOUNT_SID: ${TOLSTOY_TWILIO_ACCOUNT_SID}
      SDC_TWILIO_AUTH_TOKEN: ${TOLSTOY_TWILIO_AUTH_TOKEN}
      SDC_TWILIO_SENDER_ID: ${TOLSTOY_TWILIO_SENDER_ID}
      SDC_UPLOAD_IMAGE_URL: ${TOLSTOY_UPLOAD_IMAGE_URL}
      SDC_LANG_SERVER_URL: ${TOLSTOY_LANG_SERVER_URL}
      SDC_SESSION_COOKIE_KEY: ${TOLSTOY_SESSION_COOKIE_KEY}
      SDC_CLIENT_WEBSOCKET_URL: ${TOLSTOY_CLIENT_WEBSOCKET_URL}
      SDC_SERVER_WEBSOCKET_URL: ws://golos:${GOLOS_RPC_WS_PORT}
      SDC_CHAIN_ID: ${TOLSTOY_CHAIN_ID}
      SDC_METRICS_NAME: ${TOLSTOY_METRICS_NAME}
      SDC_METRICS_HOST: ${TOLSTOY_METRICS_HOST}
      SDC_NEWRELIC_KEY: ${TOLSTOY_NEWRELIC_KEY}
      SDC_BLOCKCYPHER_TOKEN: ${TOLSTOY_BLOCKCYPHER_TOKEN}
      SDC_IS_TESTNET: ${TOLSTOY_IS_TESTNET}
      SDC_IS_SANDBOX: ${TOLSTOY_IS_SANDBOX}
      SDC_OPENEXCHANGERATES_APP_ID: ${TOLSTOY_OPENEXCHANGERATES_APP_ID}
      SDC_SERVICE_PUSH_CLIENT_URL: ${TOLSTOY_SERVICE_PUSH_CLIENT_URL}
      TOLSTOY_GIT_TAG:
    ports:
     - "${TOLSTOY_HOST_PORT}:${TOLSTOY_PORT}"
    restart: always
volumes:
  golos_volume:
  imagehoster_cache_volume:
  tolstoy_db_volume:
  tolstoy_cache_volume:
